import { Button, VerticalBox , LineEdit, StandardListView, GroupBox} from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> results: "";
    in-out property <bool> open_curtain;
    callback divide-income(string);
    animate background { duration: 800ms; }
    title: "Calculadora de ganhos";
    icon: @image-url("./calculadora.png");
    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 25px;

        Row {
            Text {
                text: "Digite sua renda total: ";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }

        Row {
            income := LineEdit {
                font-size: 16px;
                placeholder-text: "Digite o número";
                horizontal-alignment: center;
                height: 35px;
            }
        }

        Row {
            Button {
                text: "calulate";
                primary: true;
                height: 35px;
                clicked => { 
                    root.open_curtain = !root.open_curtain;
                    divide-income(income.text);   
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: #000000;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                     //Left rectangle
                    Rectangle {
                        background: #333333;
                        x:0;
                        width: open_curtain ? 0px : (parent.width / 2);
                        height: parent.height;
                        animate width { duration: 250ms; easing: ease-in; }
                    }

                    //Right rectangle
                    Rectangle {
                        background: #333333;
                        x: open_curtain ? parent.width : (parent.width / 2);
                        width: open_curtain ? 0px : (parent.width / 2);
                        height: parent.height;
                        animate width { duration: 250ms; easing: ease-in; }
                        animate x { duration: 250ms; easing: ease-in; }
                    }
                }
            }
        }
    }
}
